version: "3.9"

services:
  postgres:
    container_name: ppgcrm_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ppgcrmuser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ppgcrmDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data    

  backend:
    container_name: ppgcrm_api
    build:
      context: .
      dockerfile: PPGCRM.API/Dockerfile
    environment:
     - JwtOptions__ExpiresInMinutes=5
     - JwtOptions__SecretKey=5i936cf0vfb6vcjzyucdpxyrh5es6oj8
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7053:80"
    depends_on:
      - postgres
 
  frontend:
    container_name: ppgcrm_frontend
    build:
      context: .Frontend/ppg-crm
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
